### ISSUE TITLE
How to fix the focal length of camera

### ISSUE THREAD

**Issue by l1346792580123** [MobileRoboticsSkoltech/RecSync-android#13]
Thanks for sharing this work! I can fix the focal length in the phone camera setting, but this app will call the phone camera itself. How can I fix the focal length of the camera?

**Comment by azaat** [comment]
Hi, thank you for the feedback! If I got you right, you are talking about [that ](https://developer.android.com/reference/android/hardware/camera2/CaptureRequest#LENS_FOCUS_DISTANCE) property of the camera. For now, we haven't included support setting fixed focus distance from UI, however, this can be modified in the code. By the way, the recording synchronization feature is getting transferred from this app to our other project, [OpenCamera Sensors](https://github.com/MobileRoboticsSkoltech/OpenCamera-Sensors). This should solve the problem of setting many manual camera controls in UI, so if you are interested, stay tuned for the updates.

**Comment by l1346792580123** [comment]
Thanks for your apply. I will try that
